# Generated by Django 5.1.4 on 2024-12-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('count', models.IntegerField(blank=True)),
                ('bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(blank=True, related_name='shopping_lists', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('current_list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_users', to='api.shoppinglist')),
                ('lists', models.ManyToManyField(blank=True, related_name='participants', to='api.shoppinglist')),
            ],
        ),
    ]
