# Generated by Django 5.1.4 on 2024-12-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_bought_alter_user_current_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought',
            field=models.BooleanField(blank=True),
        ),
    ]
