# Generated by Django 5.1.4 on 2024-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought',
            field=models.BooleanField(),
        ),
    ]
