# Generated by Django 5.1.4 on 2024-12-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shoppinglist'),
        ),
    ]
