# Generated by Django 5.1.4 on 2024-12-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_current_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='lists', to='api.shoppinglist'),
        ),
    ]
